"""Constants for the HERE Destination Weather service."""
from __future__ import annotations

from homeassistant.const import (
    DEGREE,
    UnitOfLength,
    PERCENTAGE,
    UnitOfPressure,
    UnitOfSpeed,
    UnitOfTemperature,
)
from homeassistant.components.sensor import SensorDeviceClass

NAME = "HERE Destination Weather"
DOMAIN = "here_weather"
VERSION = "4.0.7"
ISSUE_URL = "https://github.com/eifinger/hass-here-weather/issues"

STARTUP_MESSAGE = f"""
-------------------------------------------------------------------
{NAME}
Version: {VERSION}
This is a custom integration!
If you have any issues with this you need to open an issue here:
{ISSUE_URL}
-------------------------------------------------------------------
"""

DEFAULT_SCAN_INTERVAL = 1800  # 30 minutes

CONF_LANGUAGE = "language"
DEFAULT_LANGUAGE = "English - United States"

MODE_ASTRONOMY = "FORECAST_ASTRONOMY"
MODE_HOURLY = "FORECAST_HOURLY"
MODE_DAILY = "FORECAST_7DAYS"
MODE_DAILY_SIMPLE = "FORECAST_7DAYS_SIMPLE"
MODE_OBSERVATION = "OBSERVATION"
CONF_MODES = [
    MODE_ASTRONOMY,
    MODE_HOURLY,
    MODE_DAILY,
    MODE_DAILY_SIMPLE,
    MODE_OBSERVATION,
]
DEFAULT_MODE = MODE_DAILY_SIMPLE

ASTRONOMY_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "sunRise": {
        "name": "Sunrise",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
    "sunSet": {
        "name": "Sunset",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
    "moonRise": {
        "name": "Moonrise",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
    "moonSet": {
        "name": "Moonset",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
    "moonPhase": {
        "name": "Moon Phase",
        "unit_of_measurement": PERCENTAGE,
        "device_class": None,
    },
    "moonPhaseDescription": {
        "name": "Moon Phase Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "city": {"name": "City", "unit_of_measurement": None, "device_class": None},
    "latitude": {"name": "Latitude", "unit_of_measurement": None, "device_class": None},
    "longitude": {
        "name": "Longitude",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "time": {
        "name": "UTC Time",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
}

COMMON_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "daylight": {"name": "Daylight", "unit_of_measurement": None, "device_class": None},
    "description": {
        "name": "Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "skyInfo": {"name": "Sky Info", "unit_of_measurement": None, "device_class": None},
    "skyDesc": {
        "name": "Sky Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "temperatureDesc": {
        "name": "Temperature Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "comfort": {
        "name": "Comfort",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "humidity": {
        "name": "Humidity",
        "unit_of_measurement": PERCENTAGE,
        "device_class": SensorDeviceClass.HUMIDITY,
    },
    "dewPoint": {
        "name": "Dew Point",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "precipitationProbability": {
        "name": "Precipitation Probability",
        "unit_of_measurement": PERCENTAGE,
        "device_class": None,
    },
    "precipitationDesc": {
        "name": "Precipitation Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "windSpeed": {
        "name": "Wind Speed",
        "unit_of_measurement": UnitOfSpeed.KILOMETERS_PER_HOUR,
        "device_class": None,
    },
    "windDirection": {
        "name": "Wind Direction",
        "unit_of_measurement": DEGREE,
        "device_class": None,
    },
    "windDesc": {
        "name": "Wind Description",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "windDescShort": {
        "name": "Wind Description Short",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "iconName": {
        "name": "Icon Name",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "iconLink": {
        "name": "Icon Link",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "time": {
        "name": "UTC Time",
        "unit_of_measurement": None,
        "device_class": SensorDeviceClass.TIMESTAMP,
    },
}

NON_OBSERVATION_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "rainFall": {
        "name": "Rain Fall",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "snowFall": {
        "name": "Snow Fall",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "precipitationProbability": {
        "name": "Precipitation Probability",
        "unit_of_measurement": PERCENTAGE,
        "device_class": None,
    },
    "dayOfWeek": {
        "name": "Day of Week",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "weekday": {"name": "Week Day", "unit_of_measurement": None, "device_class": None},
    **COMMON_ATTRIBUTES,
}

HOURLY_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "temperature": {
        "name": "Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "airInfo": {"name": "Air Info", "unit_of_measurement": None, "device_class": None},
    "visibility": {
        "name": "Visibility",
        "unit_of_measurement": UnitOfLength.KILOMETERS,
        "device_class": None,
    },
    **NON_OBSERVATION_ATTRIBUTES,
}

DAILY_SIMPLE_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "highTemperature": {
        "name": "High Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "lowTemperature": {
        "name": "Low Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "beaufortScale": {
        "name": "Beaufort Scale",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "beaufortDescription": {
        "name": "Beaufort Scale Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "uvIndex": {"name": "UV Index", "unit_of_measurement": None, "device_class": None},
    "uvDesc": {
        "name": "UV Index Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "barometerPressure": {
        "name": "Barometric Pressure",
        "unit_of_measurement": UnitOfPressure.MBAR,
        "device_class": SensorDeviceClass.PRESSURE,
    },
    **NON_OBSERVATION_ATTRIBUTES,
}

DAILY_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "daySegment": {
        "name": "Day Segment",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "temperature": {
        "name": "Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "beaufortScale": {
        "name": "Beaufort Scale",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "beaufortDescription": {
        "name": "Beaufort Scale Description",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "visibility": {
        "name": "Visibility",
        "unit_of_measurement": UnitOfLength.KILOMETERS,
        "device_class": None,
    },
    **NON_OBSERVATION_ATTRIBUTES,
}

OBSERVATION_ATTRIBUTES: dict[str, dict[str, str | None]] = {
    "temperature": {
        "name": "Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "highTemperature": {
        "name": "High Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "lowTemperature": {
        "name": "Low Temperature",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
    },
    "precipitation1H": {
        "name": "Precipitation Over 1 Hour",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "precipitation3H": {
        "name": "Precipitation Over 3 Hours",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "precipitation6H": {
        "name": "Precipitation Over 6 Hours",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "precipitation12H": {
        "name": "Precipitation Over 12 Hours",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "precipitation24H": {
        "name": "Precipitation Over 24 Hours",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "barometerPressure": {
        "name": "Barometric Pressure",
        "unit_of_measurement": UnitOfPressure.MBAR,
        "device_class": SensorDeviceClass.PRESSURE,
    },
    "barometerTrend": {
        "name": "Barometric Pressure Trend",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "visibility": {
        "name": "Visibility",
        "unit_of_measurement": UnitOfLength.KILOMETERS,
        "device_class": None,
    },
    "snowCover": {
        "name": "Snow Cover",
        "unit_of_measurement": UnitOfLength.CENTIMETERS,
        "device_class": None,
    },
    "activeAlerts": {
        "name": "Active Alerts",
        "unit_of_measurement": None,
        "device_class": None,
    },
    "country": {"name": "Country", "unit_of_measurement": None, "device_class": None},
    "state": {"name": "State", "unit_of_measurement": None, "device_class": None},
    "city": {"name": "City", "unit_of_measurement": None, "device_class": None},
    **COMMON_ATTRIBUTES,
}

SENSOR_TYPES: dict[str, dict[str, dict[str, str | None]]] = {
    MODE_ASTRONOMY: ASTRONOMY_ATTRIBUTES,
    MODE_HOURLY: HOURLY_ATTRIBUTES,
    MODE_DAILY_SIMPLE: DAILY_SIMPLE_ATTRIBUTES,
    MODE_DAILY: DAILY_ATTRIBUTES,
    MODE_OBSERVATION: OBSERVATION_ATTRIBUTES,
}

CONDITION_CLASSES: dict[str, list[str]] = {
    "clear-night": [
        "night_passing_clouds",
        "night_mostly_clear",
        "night_clearing_skies",
        "night_clear",
    ],
    "cloudy": [
        "night_decreasing_cloudiness",
        "night_mostly_cloudy",
        "night_morning_clouds",
        "night_afternoon_clouds",
        "night_high_clouds",
        "night_high_level_clouds",
        "low_clouds",
        "overcast",
        "cloudy",
        "afternoon_clouds",
        "morning_clouds",
        "high_level_clouds",
        "high_clouds",
    ],
    "fog": [
        "night_low_level_haze",
        "night_smoke",
        "night_haze",
        "dense_fog",
        "fog",
        "light_fog",
        "early_fog",
        "early_fog_followed_by_sunny_skies",
        "low_level_haze",
        "smoke",
        "haze",
        "ice_fog",
        "hazy_sunshine",
    ],
    "hail": ["hail"],
    "lightning": [
        "night_tstorms",
        "night_scattered_tstorms",
        "scattered_tstorms",
        "night_a_few_tstorms",
        "night_isolated_tstorms",
        "night_widely_scattered_tstorms",
        "tstorms_early",
        "isolated_tstorms_late",
        "scattered_tstorms_late",
        "widely_scattered_tstorms",
        "isolated_tstorms",
        "a_few_tstorms",
    ],
    "lightning-rainy": ["thundershowers", "thunderstorms", "tstorms_late", "tstorms"],
    "partlycloudy": [
        "partly_sunny",
        "mostly_cloudy",
        "broken_clouds",
        "more_clouds_than_sun",
        "night_broken_clouds",
        "increasing_cloudiness",
        "night_partly_cloudy",
        "night_scattered_clouds",
        "passing_clounds",
        "more_sun_than_clouds",
        "scattered_clouds",
        "partly_cloudy",
        "a_mixture_of_sun_and_clouds",
        "increasing_cloudiness",
        "decreasing_cloudiness",
        "clearing_skies",
        "breaks_of_sun_late",
    ],
    "pouring": [
        "heavy_rain_late",
        "heavy_rain_early",
        "tons_of_rain",
        "lots_of_rain",
        "heavy_rain",
        "heavy_rain_early",
        "heavy_rain_early",
    ],
    "rainy": [
        "rain_late",
        "showers_late",
        "rain_early",
        "showery",
        "showers_early",
        "numerous_showers",
        "rain",
        "light_rain_late",
        "sprinkles_late",
        "light_rain_early",
        "sprinkles_early",
        "light_rain",
        "sprinkles",
        "drizzle",
        "night_showers",
        "night_sprinkles",
        "night_rain_showers",
        "night_passing_showers",
        "night_light_showers",
        "night_a_few_showers",
        "night_scattered_showers",
        "rain_early",
        "scattered_showers",
        "a_few_showers",
        "light_showers",
        "passing_showers",
        "rain_showers",
        "showers",
    ],
    "snowy": [
        "heavy_snow_late",
        "heavy_snow_early",
        "heavy_snow",
        "snow_late",
        "snow_early",
        "moderate_snow",
        "snow",
        "light_snow_late",
        "snow_showers_late",
        "flurries_late",
        "light_snow_early",
        "flurries_early",
        "light_snow",
        "snow_flurries",
        "sleet",
        "an_icy_mix_changing_to_snow",
        "an_icy_mix_changing_to_rain",
        "rain_changing_to_snow",
        "icy_mix_early",
        "light_icy_mix_late",
        "icy_mix_late",
        "scattered_flurries",
    ],
    "snowy-rainy": [
        "freezing_rain",
        "light_freezing_rain",
        "snow_showers_early",
        "snow_showers",
        "light_snow_showers",
        "snow_rain_mix",
        "light_icy_mix_early",
        "rain_changing_to_an_icy_mix",
        "snow_changing_to_an_icy_mix",
        "snow_changing_to_rain",
        "heavy_mixture_of_precip",
        "light_mixture_of_precip",
        "icy_mix",
        "mixture_of_precip",
    ],
    "sunny": ["sunny", "clear", "mostly_sunny", "mostly_clear"],
    "windy": ["strong_thunderstorms", "severe_thunderstorms"],
    "windy-variant": [],
    "exceptional": [
        "blizzard",
        "snowstorm",
        "duststorm",
        "sandstorm",
        "hurricane",
        "tropical_storm",
        "flood",
        "flash_floods",
        "tornado",
    ],
}

LANGUAGES: dict[str, str] = {
    "Afar - Djibouti": "aa-DJ",
    "Afar - Eritrea": "aa-ER",
    "Afar - Ethiopia": "aa-ET",
    "Afrikaans - Namibia": "af-NA",
    "Afrikaans - South Africa": "af-ZA",
    "Akan - Ghana": "ak-GH",
    "Albanian - Albania": "sq-AL",
    "Albanian - North Macedonia": "sq-MK",
    "Amharic - Ethiopia": "am-ET",
    "Arabic - Algeria": "ar-DZ",
    "Arabic - Bahrain": "ar-BH",
    "Arabic - Chad": "ar-TD",
    "Arabic - Comoros": "ar-KM",
    "Arabic - Djibouti": "ar-DJ",
    "Arabic - Egypt": "ar-EG",
    "Arabic - Eritrea": "ar-ER",
    "Arabic - Iraq": "ar-IQ",
    "Arabic - Israel": "ar-IL",
    "Arabic - Jordan": "ar-JO",
    "Arabic - Kuwait": "ar-KW",
    "Arabic - Lebanon": "ar-LB",
    "Arabic - Libya": "ar-LY",
    "Arabic - Mauritania": "ar-MR",
    "Arabic - Morocco": "ar-MA",
    "Arabic - Oman": "ar-OM",
    "Arabic - Palestinian Authority": "ar-PS",
    "Arabic - Qatar": "ar-QA",
    "Arabic - Saudi Arabia": "ar-SA",
    "Arabic - Somalia": "ar-SO",
    "Arabic - South Sudan": "ar-SS",
    "Arabic - Sudan": "ar-SD",
    "Arabic - Syria": "ar-SY",
    "Arabic - Tunisia": "ar-TN",
    "Arabic - U.A.E.": "ar-AE",
    "Arabic - Yemen": "ar-YE",
    "Armenian - Armenia": "hy-AM",
    "Assamese - India": "as-IN",
    "Bangla - Bangladesh": "bn-BD",
    "Bangla - India": "bn-IN",
    "Bashkir - Russia": "ba-RU",
    "Basque - Spain": "eu-ES",
    "Belarusian - Belarus": "be-BY",
    "Bulgarian - Bulgaria": "bg-BG",
    "Burmese - Myanmar": "my-MM",
    "Catalan - Andorra": "ca-AD",
    "Catalan - France": "ca-FR",
    "Catalan - Italy": "ca-IT",
    "Catalan - Spain": "ca-ES",
    "Chinese (Simplified) - People's Republic of China": "zh-CN",
    "Chinese (Simplified) - Singapore": "zh-SG",
    "Chinese (Traditional) - Hong Kong S.A.R.": "zh-HK",
    "Chinese (Traditional) - Macao S.A.R.": "zh-MO",
    "Chinese (Traditional) - Taiwan": "zh-TW",
    "Church Slavic - Russia": "cu-RU",
    "Cornish - United Kingdom": "kw-GB",
    "Corsican - France": "co-FR",
    "Croatian - Croatia": "hr-HR",
    "Croatian (Latin) - Bosnia and Herzegovina": "hr-BA",
    "Czech - Czech Republic": "cs-CZ",
    "Danish - Denmark": "da-DK",
    "Danish - Greenland": "da-GL",
    "Divehi - Maldives": "dv-MV",
    "Dutch - Aruba": "nl-AW",
    "Dutch - Belgium": "nl-BE",
    "Dutch - Bonaire, Sint Eustatius and Saba": "nl-BQ",
    "Dutch - Curaçao": "nl-CW",
    "Dutch - Netherlands": "nl-NL",
    "Dutch - Sint Maarten": "nl-SX",
    "Dutch - Suriname": "nl-SR",
    "Dzongkha - Bhutan": "dz-BT",
    "English - American Samoa": "en-AS",
    "English - Anguilla": "en-AI",
    "English - Antigua and Barbuda": "en-AG",
    "English - Australia": "en-AU",
    "English - Austria": "en-AT",
    "English - Bahamas": "en-BS",
    "English - Barbados": "en-BB",
    "English - Belgium": "en-BE",
    "English - Belize": "en-BZ",
    "English - Bermuda": "en-BM",
    "English - Botswana": "en-BW",
    "English - British Indian Ocean Territory": "en-IO",
    "English - British Virgin Islands": "en-VG",
    "English - Burundi": "en-BI",
    "English - Cameroon": "en-CM",
    "English - Canada": "en-CA",
    "English - Cayman Islands": "en-KY",
    "English - Christmas Island": "en-CX",
    "English - Cocos [Keeling] Islands": "en-CC",
    "English - Cook Islands": "en-CK",
    "English - Cyprus": "en-CY",
    "English - Denmark": "en-DK",
    "English - Dominica": "en-DM",
    "English - Eritrea": "en-ER",
    "English - Falkland Islands": "en-FK",
    "English - Finland": "en-FI",
    "English - Fiji": "en-FJ",
    "English - Gambia": "en-GM",
    "English - Germany": "en-DE",
    "English - Ghana": "en-GH",
    "English - Gibraltar": "en-GI",
    "English - Grenada": "en-GD",
    "English - Guam": "en-GU",
    "English - Guernsey": "en-GG",
    "English - Guyana": "en-GY",
    "English - Hong Kong": "en-HK",
    "English - India": "en-IN",
    "English - Ireland": "en-IE",
    "English - Isle of Man": "en-IM",
    "English - Israel": "en-IL",
    "English - Jamaica": "en-JM",
    "English - Jersey": "en-JE",
    "English - Kenya": "en-KE",
    "English - Kiribati": "en-KI",
    "English - Lesotho": "en-LS",
    "English - Liberia": "en-LR",
    "English - Macao SAR": "en-MO",
    "English - Madagascar": "en-MG",
    "English - Malawi": "en-MW",
    "English - Malaysia": "en-MY",
    "English - Malta": "en-MT",
    "English - Marshall Islands": "en-MH",
    "English - Mauritius": "en-MU",
    "English - Micronesia": "en-FM",
    "English - Montserrat": "en-MS",
    "English - Namibia": "en-NA",
    "English - Nauru": "en-NR",
    "English - Netherlands": "en-NL",
    "English - New Zealand": "en-NZ",
    "English - Nigeria": "en-NG",
    "English - Niue": "en-NU",
    "English - Norfolk Island": "en-NF",
    "English - Northern Mariana Islands": "en-MP",
    "English - Pakistan": "en-PK",
    "English - Palau": "en-PW",
    "English - Papua New Guinea": "en-PG",
    "English - Pitcairn Islands": "en-PN",
    "English - Puerto Rico": "en-PR",
    "English - Republic of the Philippines": "en-PH",
    "English - Rwanda": "en-RW",
    "English - Saint Kitts and Nevis": "en-KN",
    "English - Saint Lucia": "en-LC",
    "English - Saint Vincent and the Grenadines": "en-VC",
    "English - Samoa": "en-WS",
    "English - Seychelles": "en-SC",
    "English - Sierra Leone": "en-SL",
    "English - Singapore": "en-SG",
    "English - Sint Maarten": "en-SX",
    "English - Slovenia": "en-SI",
    "English - Solomon Islands": "en-SB",
    "English - South Africa": "en-ZA",
    "English - South Sudan": "en-SS",
    "English - St Helena, Ascension, Tristan da Cunha": "en-SH",
    "English - Sudan": "en-SD",
    "English - Swaziland": "en-SZ",
    "English - Sweden": "en-SE",
    "English - Switzerland": "en-CH",
    "English - Tanzania": "en-TZ",
    "English - Tokelau": "en-TK",
    "English - Tonga": "en-TO",
    "English - Trinidad and Tobago": "en-TT",
    "English - Turks and Caicos Islands": "en-TC",
    "English - Tuvalu": "en-TV",
    "English - Uganda": "en-UG",
    "English - United Arab Emirates": "en-AE",
    "English - United Kingdom": "en-GB",
    "English - United States": "en-US",
    "English - US Minor Outlying Islands": "en-UM",
    "English - US Virgin Islands": "en-VI",
    "English - Vanuatu": "en-VU",
    "English - Zambia": "en-ZM",
    "English - Zimbabwe": "en-ZW",
    "Estonian - Estonia": "et-EE",
    "Ewe - Ghana": "ee-GH",
    "Ewe - Togo": "ee-TG",
    "Faroese - Denmark": "fo-DK",
    "Faroese - Faroe Islands": "fo-FO",
    "Finnish - Finland": "fi-FI",
    "French - Algeria": "fr-DZ",
    "French - Belgium": "fr-BE",
    "French - Benin": "fr-BJ",
    "French - Burkina Faso": "fr-BF",
    "French - Burundi": "fr-BI",
    "French - Cameroon": "fr-CM",
    "French - Canada": "fr-CA",
    "French - Central African Republic": "fr-CF",
    "French - Chad": "fr-TD",
    "French - Comoros": "fr-KM",
    "French - Congo": "fr-CG",
    "French - Congo, DRC": "fr-CD",
    "French - Côte d'Ivoire": "fr-CI",
    "French - Djibouti": "fr-DJ",
    "French - Equatorial Guinea": "fr-GQ",
    "French - France": "fr-FR",
    "French - French Guiana": "fr-GF",
    "French - French Polynesia": "fr-PF",
    "French - Gabon": "fr-GA",
    "French - Guadeloupe": "fr-GP",
    "French - Guinea": "fr-GN",
    "French - Haiti": "fr-HT",
    "French - Luxembourg": "fr-LU",
    "French - Madagascar": "fr-MG",
    "French - Mali": "fr-ML",
    "French - Martinique": "fr-MQ",
    "French - Mauritania": "fr-MR",
    "French - Mauritius": "fr-MU",
    "French - Mayotte": "fr-YT",
    "French - Morocco": "fr-MA",
    "French - New Caledonia": "fr-NC",
    "French - Niger": "fr-NE",
    "French - Principality of Monaco": "fr-MC",
    "French - Reunion": "fr-RE",
    "French - Rwanda": "fr-RW",
    "French - Saint Barthélemy": "fr-BL",
    "French - Saint Martin": "fr-MF",
    "French - Saint Pierre and Miquelon": "fr-PM",
    "French - Senegal": "fr-SN",
    "French - Seychelles": "fr-SC",
    "French - Switzerland": "fr-CH",
    "French - Syria": "fr-SY",
    "French - Togo": "fr-TG",
    "French - Tunisia": "fr-TN",
    "French - Vanuatu": "fr-VU",
    "French - Wallis and Futuna": "fr-WF",
    "Frisian - Netherlands": "fy-NL",
    "Fulah - Cameroon": "ff-CM",
    "Fulah - Guinea": "ff-GN",
    "Fulah - Mauritania": "ff-MR",
    "Fulah - Nigeria": "ff-NG",
    "Galician - Spain": "gl-ES",
    "Ganda - Uganda": "lg-UG",
    "Georgian - Georgia": "ka-GE",
    "German - Austria": "de-AT",
    "German - Belgium": "de-BE",
    "German - Germany": "de-DE",
    "German - Italy": "de-IT",
    "German - Liechtenstein": "de-LI",
    "German - Luxembourg": "de-LU",
    "German - Switzerland": "de-CH",
    "Greek - Cyprus": "el-CY",
    "Greek - Greece": "el-GR",
    "Greenlandic - Greenland": "kl-GL",
    "Guarani - Paraguay": "gn-PY",
    "Gujarati - India": "gu-IN",
    "Hebrew - Israel": "he-IL",
    "Hindi - India": "hi-IN",
    "Hungarian - Hungary": "hu-HU",
    "Icelandic - Iceland": "is-IS",
    "Igbo - Nigeria": "ig-NG",
    "Indonesian - Indonesia": "id-ID",
    "Interlingua - France": "ia-FR",
    "Irish - Ireland": "ga-IE",
    "Italian - Italy": "it-IT",
    "Italian - San Marino": "it-SM",
    "Italian - Switzerland": "it-CH",
    "Italian - Vatican City": "it-VA",
    "Japanese - Japan": "ja-JP",
    "Kannada - India": "kn-IN",
    "Kazakh - Kazakhstan": "kk-KZ",
    "Khmer - Cambodia": "km-KH",
    "Kikuyu - Kenya": "ki-KE",
    "Kinyarwanda - Rwanda": "rw-RW",
    "Kiswahili - Kenya": "sw-KE",
    "Kiswahili - Tanzania": "sw-TZ",
    "Kiswahili - Uganda": "sw-UG",
    "Korean - Korea": "ko-KR",
    "Korean - North Korea": "ko-KP",
    "Kyrgyz - Kyrgyzstan": "ky-KG",
    "Lao - Lao P.D.R.": "lo-LA",
    "Latvian - Latvia": "lv-LV",
    "Lingala - Angola": "ln-AO",
    "Lingala - Central African Republic": "ln-CF",
    "Lingala - Congo": "ln-CG",
    "Lingala - Congo DRC": "ln-CD",
    "Lithuanian - Lithuania": "lt-LT",
    "Luba-Katanga - Congo DRC": "lu-CD",
    "Luxembourgish - Luxembourg": "lb-LU",
    "Macedonian - North Macedonia": "mk-MK",
    "Malagasy - Madagascar": "mg-MG",
    "Malay - Brunei Darussalam": "ms-BN",
    "Malay - Malaysia": "ms-MY",
    "Malayalam - India": "ml-IN",
    "Maltese - Malta": "mt-MT",
    "Manx - Isle of Man": "gv-IM",
    "Maori - New Zealand": "mi-NZ",
    "Marathi - India": "mr-IN",
    "Nepali - India": "ne-IN",
    "Nepali - Nepal": "ne-NP",
    "North Ndebele - Zimbabwe": "nd-ZW",
    "Norwegian (Bokmal) - Norway": "nb-NO",
    "Norwegian (Nynorsk) - Norway": "nn-NO",
    "Norwegian Bokmål - Svalbard and Jan Mayen": "nb-SJ",
    "Occitan - France": "oc-FR",
    "Odia - India": "or-IN",
    "Oromo - Ethiopia": "om-ET",
    "Oromo - Kenya": "om-KE",
    "Ossetian - Cyrillic, Georgia": "os-GE",
    "Ossetian - Cyrillic, Russia": "os-RU",
    "Pashto - Afghanistan": "ps-AF",
    "Pashto - Pakistan": "ps-PK",
    "Persian - Afghanistan": "fa-AF",
    "Persian - Iran": "fa-IR",
    "Polish - Poland": "pl-PL",
    "Portuguese - Angola": "pt-AO",
    "Portuguese - Brazil": "pt-BR",
    "Portuguese - Cabo Verde": "pt-CV",
    "Portuguese - Equatorial Guinea": "pt-GQ",
    "Portuguese - Guinea-Bissau": "pt-GW",
    "Portuguese - Luxembourg": "pt-LU",
    "Portuguese - Macao SAR": "pt-MO",
    "Portuguese - Mozambique": "pt-MZ",
    "Portuguese - Portugal": "pt-PT",
    "Portuguese - São Tomé and Príncipe": "pt-ST",
    "Portuguese - Switzerland": "pt-CH",
    "Portuguese - Timor-Leste": "pt-TL",
    "Punjabi - India": "pa-IN",
    "Romanian - Moldova": "ro-MD",
    "Romanian - Romania": "ro-RO",
    "Romansh - Switzerland": "rm-CH",
    "Rundi - Burundi": "rn-BI",
    "Russian - Belarus": "ru-BY",
    "Russian - Kazakhstan": "ru-KZ",
    "Russian - Kyrgyzstan": "ru-KG",
    "Russian - Moldova": "ru-MD",
    "Russian - Russia": "ru-RU",
    "Russian - Ukraine": "ru-UA",
    "Sami (Northern) - Finland": "se-FI",
    "Sami (Northern) - Norway": "se-NO",
    "Sami (Northern) - Sweden": "se-SE",
    "Sango - Central African Republic": "sg-CF",
    "Sanskrit - India": "sa-IN",
    "Scottish Gaelic - United Kingdom": "gd-GB",
    "Slovak - Slovakia": "sk-SK",
    "Slovenian - Slovenia": "sl-SI",
    "Somali - Djibouti": "so-DJ",
    "Somali - Ethiopia": "so-ET",
    "Somali - Kenya": "so-KE",
    "Somali - Somalia": "so-SO",
    "Sotho - South Africa": "st-ZA",
    "South Ndebele - South Africa": "nr-ZA",
    "Southern Sotho - Lesotho": "st-LS",
    "Spanish - Argentina": "es-AR",
    "Spanish - Belize": "es-BZ",
    "Spanish - Bolivarian Republic of Venezuela": "es-VE",
    "Spanish - Bolivia": "es-BO",
    "Spanish - Brazil": "es-BR",
    "Spanish - Chile": "es-CL",
    "Spanish - Colombia": "es-CO",
    "Spanish - Costa Rica": "es-CR",
    "Spanish - Cuba": "es-CU",
    "Spanish - Dominican Republic": "es-DO",
    "Spanish - Ecuador": "es-EC",
    "Spanish - El Salvador": "es-SV",
    "Spanish - Equatorial Guinea": "es-GQ",
    "Spanish - Guatemala": "es-GT",
    "Spanish - Honduras": "es-HN",
    "Spanish - Mexico": "es-MX",
    "Spanish - Nicaragua": "es-NI",
    "Spanish - Panama": "es-PA",
    "Spanish - Paraguay": "es-PY",
    "Spanish - Peru": "es-PE",
    "Spanish - Philippines": "es-PH",
    "Spanish - Puerto Rico": "es-PR",
    "Spanish - Spain": "es-ES",
    "Spanish - United - States": "es-US",
    "Spanish - Uruguay": "es-UY",
    "Swati - South Africa": "ss-ZA",
    "Swati - Swaziland": "ss-SZ",
    "Swedish - Åland Islands": "sv-AX",
    "Swedish - Finland": "sv-FI",
    "Swedish - Sweden": "sv-SE",
    "Tamil - India": "ta-IN",
    "Tamil - Malaysia": "ta-MY",
    "Tamil - Singapore": "ta-SG",
    "Tamil - Sri Lanka": "ta-LK",
    "Tatar - Russia": "tt-RU",
    "Telugu - India": "te-IN",
    "Thai - Thailand": "th-TH",
    "Tibetan - India": "bo-IN",
    "Tibetan - People's Republic of China": "bo-CN",
    "Tigrinya - Eritrea": "ti-ER",
    "Tigrinya - Ethiopia": "ti-ET",
    "Tongan - Tonga": "to-TO",
    "Tsonga - South Africa": "ts-ZA",
    "Turkish - Cyprus": "tr-CY",
    "Turkish - Turkey": "tr-TR",
    "Turkmen - Turkmenistan": "tk-TM",
    "Ukrainian - Ukraine": "uk-UA",
    "Urdu - India": "ur-IN",
    "Urdu - Islamic Republic of Pakistan": "ur-PK",
    "Uyghur - People's Republic of China": "ug-CN",
    "Wolof - Senegal": "wo-SN",
    "Xhosa - South Africa": "xh-ZA",
    "Yi - People's Republic of China": "ii-CN",
    "Yoruba - Benin": "yo-BJ",
    "Yoruba - Nigeria": "yo-NG",
    "Zulu - South Africa": "zu-ZA",
}
